name: open_street_map_search_and_pick
description: A flutter place search and location picker plugin that uses Open Street Map.
version: 0.1.0
homepage: https://github.com/AbduzZami/open_street_map_search_and_pick.git

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_map: ^3.0.0
  geolocator: ^9.0.2
  http: ^0.13.5
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
